### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by kaelig**
- [new] Unit tests using Jasmine-style BDD Sass testing framework [Bootcamp](https://github.com/thejameskyle/bootcamp)

screen shot 2014-02-26 at 22 22 55

### CODE REVIEW

**Comment by kaelig** [comment]
/cc @thejameskyle thanks for Bootcamp, here is my first attempt at using it. Seems awesome so far even if I encountered a couple of bugs.

Any feedback on this pull request would be greatly appreciated.

**Comment by jamiebuilds** [comment]
I'm just going to link to you to the response I just made to a bootcamp issue because I'm on my phone. I hope it's helpful

https://github.com/thejameskyle/bootcamp/issues/89#issuecomment-36189950

**Comment by kaelig** [comment]
Thanks @thejameskyle. The logic was already separated into a function so I could test it quite easily.  If you have a chance to later have a peek at the pull-request itself in case there is something shocking it would be awesome.

**Comment by jamiebuilds** [comment]
No, I don't see anything shocking. I was assuming you were asking because there was something more in the mixin you wanted to test.

In the interest of transparency, Bootcamp is going to go through a [major facelift](https://github.com/thejameskyle/bootcamp/issues/75) soon that will see some breaking changes. Your tests will be simplified to this syntax:

``` scss
@include describe("Remify") {
  @include it("should convert pixel values into rems") {
    @include expect( rem(10px) to equal 1rem );
  }
  // ...
}
```

**Comment by kaelig** [comment]
I've seen that, looking forward to testing Bootcamp v2. Thanks for your feedback and keep up the good work!

**Pull request merged**
